import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Provider from "./provider";
import LandingPage from "./LandingPage/page";
import { Toaster } from "react-hot-toast";
import AuthWatcher from "./workspace/_components/AuthWatcher";
import ChatBot from "./workspace/_components/ChatBot";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "AI tutor",
  description: "Generated by create next app",
};
const clearAppearance = {
  variables: {
    colorPrimary: "#22c55e",
    colorText: "#ffffff",
    colorBackground: "#1d1f2b",
    colorInputBackground: "#2a2d3c",
    colorInputText: "#ffffff",
    colorBorder: "#ffffff",
    colorInputText: "#fff",
    socialButtonsBlackButton: "#fff"
  }
}
export default function RootLayout({ children }) {
  return (
    <ClerkProvider  appearance={clearAppearance}>
      
      <html lang="en">
        <body
         className="overflow-x-hidden  w-full bg-black"
        >
        
         <Provider>{children}</Provider>
         <AuthWatcher/>
         <ChatBot/>
        <Toaster
         position="top-right"
            toastOptions={{
              duration: 3000,
              style: {
                background: "#161B22",
                color: "#fff",
                border: "1px solid #1a1f29",
                borderRadius: "10px",
                padding: "12px 16px",
              },
            }}
        />
      </body>
    </html>
  
    </ClerkProvider>
  );
}