import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Provider from "./provider";
import LandingPage from "./LandingPage/page";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "AI tutor",
  description: "Generated by create next app",
};
const clearAppearance = {
  variables: {
    colorPrimary: "#22c55e",
    colorText: "#ffffff",
    colorBackground: "#1d1f2b",
    colorInputBackground: "#2a2d3c",
    colorInputText: "#ffffff",
    colorBorder: "#ffffff",
    colorInputText: "#fff",
    socialButtonsBlackButton: "#fff"
  }
}
export default function RootLayout({ children }) {
  return (
    <ClerkProvider  appearance={clearAppearance}>
      
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        
         <Provider>{children}</Provider>
         
      </body>
    </html>
  
    </ClerkProvider>
  );
}